name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    Build:
        strategy:
            matrix:
                options:
                    - os: ubuntu-latest
                      framework: netcoreapp2.1
                      runtime: -x64
                      codecov: false
                    - os: windows-latest
                      framework: netcoreapp2.1
                      runtime: -x64
                      codecov: false

        runs-on: ${{matrix.options.os}}

        steps:
            - uses: actions/checkout@v2

            - name: Install NuGet
              uses: NuGet/setup-nuget@v1

            - name: Build
              shell: pwsh
              run: dotnet build -c Release -f ${{matrix.options.framework}}

            - name: Test
              shell: pwsh
              run: dotnet test -c -f ${{matrix.options.framework}}