name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    Build:
        strategy:
            matrix:
                options:
                    - os: ubuntu-latest
                      framework: netcoreapp2.1
                    - os: windows-latest
                      framework: netcoreapp2.1

        runs-on: ${{matrix.options.os}}

        steps:
            - uses: actions/checkout@v2

            - name: Install NuGet
              uses: NuGet/setup-nuget@v1

            - name: Build
              shell: pwsh
              run: dotnet build -c Release -f ${{matrix.options.framework}}

            - name: Test
              shell: pwsh
              run: dotnet test -f ${{matrix.options.framework}}